### ISSUE TITLE
页面上没有显示。

### ISSUE THREAD

**Issue by Attiv** [foamzou/bilibili-downloader#1]
![CleanShot 2023-06-27 at 17 51 54@2x](https://github.com/foamzou/bilibili-downloader/assets/15698129/63fb2570-b820-490b-9832-1ad8d65c556b)
在这个视频上： 【【ai孙燕姿】翻唱合集（持续更新）】 https://www.bilibili.com/video/BV13c411K7bN/?share_source=copy_web&vd_source=09465ec5aa6052962086b991ce304474

**Comment by Jayz945** [comment]
101行toolbar-left改成video-toolbar-left。 官方多了个前缀video-

**Comment by foamzou** [comment]
Fixed
