### ISSUE TITLE
404 报错

### ISSUE THREAD

**Issue by bxrjmfh** [foamzou/bilibili-downloader#4]
网址：https://www.bilibili.com/video/BV1CEDkYtEGR/?spm_id_from=333.337.search-card.all.click&vd_source=9900fa7e7dd2fb270b62937cbae83988
现象：
![image](https://github.com/user-attachments/assets/0bda5880-bbf0-41ed-997c-28c450217c0c)

**Comment by foamzou** [comment]
Fixed. 视频 title 有些编码问题，已移除。
